name: Testing
on:
  push:
    branches:
    - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name : permsi
        run: chmod 755 .github/scripts/test_swift_package.sh
      - name: Testing Swift package
        run: exec ./.github/scripts/test_swift_package.sh

      - name : permsi
        run: chmod 755 .github/scripts/test_app.sh

      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh


